# -*- coding: utf-8 -*-
"""Copy of MOVIERECOMMENDATIONUSINGKNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YxaacHF1Bi7O-RoljPSRHPIgXx3pxPwH

IMPORTING MODULES
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Data Collection and Understanding"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df_movies = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data science/tmdb_5000_movies.csv')
df_credits = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data science/tmdb_5000_credits.csv')

print("Movies columns:", df_movies.columns.tolist())
print("Credits columns:", df_credits.columns.tolist())

df_merged = pd.merge(df_movies, df_credits, left_on='id', right_on='movie_id', how='inner')  # 'inner' keeps only matching rows

print(f"Shape before merge: Movies={df_movies.shape}, Credits={df_credits.shape}")
print(f"Shape after merge: {df_merged.shape}")
print("\nSample merged data:")
df_merged.head(2)

df_merged.info()

df_merged.describe()

df_merged.isnull().sum()

"""DATA CLEANING"""

df_merged = df_merged.dropna(thresh=len(df_merged.columns) * 0.8, axis=0)

df_merged = df_merged.dropna(thresh=len(df_merged.columns) * 0.8, axis=0)

#checking outlier
import seaborn as sns
import matplotlib.pyplot as plt
print("Columns in df_merged:", df_merged.columns.tolist())

# Load the movies dataset
df_movies = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data science/tmdb_5000_movies.csv')

# Display the first few rows and information about the dataframe
print("Movies dataset loaded successfully.")
print("\nFirst 5 rows:")
display(df_movies.head())
print("\nDataFrame Info:")
df_movies.info()

# Merge df_movies and df_credits on 'movie_id'
# We'll use an inner merge to keep only movies present in both datasets
df_merged = pd.merge(df_movies, df_credits, left_on='id', right_on='movie_id', how='inner')

# Drop the duplicate title column and the extra movie_id column from the credits dataframe
df_merged = df_merged.drop(['title_y', 'movie_id'], axis=1)

# Rename columns for clarity
df_merged = df_merged.rename(columns={'title_x': 'title', 'id': 'movie_id'})

# Display the first few rows and information about the merged dataframe
print("DataFrames merged successfully.")
print("\nFirst 5 rows of merged DataFrame:")
display(df_merged.head())
print("\nMerged DataFrame Info:")
df_merged.info()

import pandas as pd

# Sample data - replace this with your actual DataFrame loading
data = {
    'title': ['Movie1', 'Movie2', 'Movie3'],
    'genres': [
        '[{"id": 28, "name": "Action"}, {"id": 35, "name": "Comedy"}]',
        '[{"id": 18, "name": "Drama"}]',
        '[{"id": 28, "name": "Action"}, {"id": 18, "name": "Drama"}]'
    ],
    'vote_average': [6.5, 7.2, 8.1]
}
df = pd.DataFrame(data)

# 1. Extract genres (simplified)
df['genres_list'] = df['genres'].str.findall(r'"name": "(.*?)"')

# 2. Create binary genre columns
df['action'] = df['genres_list'].apply(lambda x: 1 if 'Action' in x else 0)
df['comedy'] = df['genres_list'].apply(lambda x: 1 if 'Comedy' in x else 0)
df['drama'] = df['genres_list'].apply(lambda x: 1 if 'Drama' in x else 0)

# 3. Create target (1 if rating >=7, else 0)
df['recommend'] = (df['vote_average'] >= 7).astype(int)

# Show results
print(df[['title', 'action', 'comedy', 'drama', 'recommend']])

"""Visualisation"""

plt.figure(figsize=(15, 5))

# Budget vs Revenue
plt.subplot(1, 3, 1)
sns.scatterplot(x='budget', y='revenue', data=df_merged, alpha=0.6)
plt.title('Budget vs Revenue')
plt.xscale('log')
plt.yscale('log')

# Popularity vs Vote Average
plt.subplot(1, 3, 2)
sns.scatterplot(x='popularity', y='vote_average', data=df_merged, alpha=0.6)
plt.title('Popularity vs Vote Average')

# Runtime vs Vote Average
plt.subplot(1, 3, 3)
sns.scatterplot(x='runtime', y='vote_average', data=df_merged, alpha=0.6)
plt.title('Runtime vs Vote Average')

plt.tight_layout()
plt.show()

# Extract year from release date
df_merged['release_year'] = pd.to_datetime(df_merged['release_date']).dt.year

plt.figure(figsize=(15, 5))

# Movies per year
plt.subplot(1, 3, 1)
df_merged['release_year'].value_counts().sort_index().plot()
plt.title('Movies Released per Year')
plt.xlabel('Year')
plt.ylabel('Number of Movies')

# Average budget over time
plt.subplot(1, 3, 2)
df_merged.groupby('release_year')['budget'].mean().plot()
plt.title('Average Budget Over Time')
plt.xlabel('Year')
plt.ylabel('Average Budget')

# Average popularity over time
plt.subplot(1, 3, 3)
df_merged.groupby('release_year')['popularity'].mean().plot()
plt.title('Average Popularity Over Time')
plt.xlabel('Year')
plt.ylabel('Average Popularity')

plt.tight_layout()
plt.show()

# Top production countries (after extracting from JSON)
import ast

def get_production_countries(x):
    try:
        countries = ast.literal_eval(x)
        return [country['name'] for country in countries]
    except:
        return []

df_merged['production_countries_list'] = df_merged['production_companies'].apply(get_production_countries)

# Flatten the list of countries
all_countries = [country for sublist in df_merged['production_countries_list'] for country in sublist]
country_counts = pd.Series(all_countries).value_counts().head(10)

plt.figure(figsize=(12, 6))
sns.barplot(x=country_counts.values, y=country_counts.index)
plt.title('Top 10 Production Countries')
plt.xlabel('Number of Movies')
plt.show()

# Extract genres from JSON
def get_genres(x):
    try:
        genres = ast.literal_eval(x)
        return [genre['name'] for genre in genres]
    except:
        return []

df_merged['genres_list'] = df_merged['genres'].apply(get_genres)

# Genre popularity
all_genres = [genre for sublist in df_merged['genres_list'] for genre in sublist]
genre_counts = pd.Series(all_genres).value_counts()

plt.figure(figsize=(12, 6))
sns.barplot(x=genre_counts.values, y=genre_counts.index)
plt.title('Most Common Genres')
plt.xlabel('Number of Movies')
plt.show()

# Genre vs Average Revenue
genre_revenue = {}
for genre in genre_counts.index:
    mask = df_merged['genres_list'].apply(lambda x: genre in x)
    genre_revenue[genre] = df_merged[mask]['revenue'].mean()

genre_revenue = pd.Series(genre_revenue).sort_values(ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x=genre_revenue.values, y=genre_revenue.index)
plt.title('Average Revenue by Genre')
plt.xlabel('Average Revenue')
plt.show()

# Select numerical features
numerical_features = ['budget', 'popularity', 'revenue', 'runtime', 'vote_average', 'vote_count']

plt.figure(figsize=(10, 8))
corr_matrix = df_merged[numerical_features].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', center=0)
plt.title('Correlation Heatmap of Numerical Features')
plt.show()

"""Data Preprocessing"""

import pandas as pd
from sklearn.preprocessing import StandardScaler

# Sample data with continuous genre scores (0-10 scale)
data = {
    'movie_id': [1, 2, 3, 4],
    'action': [8.2, 2.1, 6.7, 9.0],  # Continuous values
    'comedy': [1.5, 9.8, 3.2, 0.5],  # Continuous values
    'drama': [4.0, 7.2, 5.5, 3.8]    # Continuous values
}
df_merged = pd.DataFrame(data)

# Scale the continuous genre features
scaler = StandardScaler()
df_merged[['action', 'comedy', 'drama']] = scaler.fit_transform(df_merged[['action', 'comedy', 'drama']])

# Display scaled values
print(df_merged[['movie_id', 'action', 'comedy', 'drama']])

# Scale features (critical for KNN)
# This code is moved to the previous cell where X_train and X_test are defined.

"""Implementation of KNN"""

import pandas as pd
from sklearn.neighbors import KNeighborsClassifier  # 👈 Changed to Classifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

# Sample data (replace with your actual dataset)
data = {
    'movie_id': [1, 2, 3, 4, 5],
    'action': [1, 0, 1, 0, 1],
    'comedy': [0, 1, 1, 0, 0],
    'drama': [0, 0, 1, 1, 0],
    'avg_rating': [4.5, 3.8, 4.2, 4.0, 3.5]  # Convert to binary class
}

movies = pd.DataFrame(data)

# Convert ratings to binary class (1 if rating ≥ 4.0, else 0)
movies['recommend'] = (movies['avg_rating'] >= 4.0).astype(int)  # 👈 New target

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Assuming 'movies' is your DataFrame with the following columns:
# 'action', 'comedy', 'drama' (features), and 'recommend' (target 0/1)

# Correct way to select multiple columns for features
X = movies[['action', 'comedy', 'drama']]  # Note double brackets for multiple columns
y = movies['recommend']  # Binary target

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X,y ,test_size=0.2,random_state=42) # Preserves class distribution in splits # Removed stratify=y
# Check shapes
print("Training set shapes:")
print(f"X_train: {X_train.shape}, y_train: {y_train.shape}")
print("\nTest set shapes:")
print(f"X_test: {X_test.shape}, y_test: {y_test.shape}")

# Scale features (only if features are continuous values)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  # Fit on train, then transform
X_test_scaled = scaler.transform(X_test)       # Only transform test set

# Verify scaling worked
print("\nScaled features summary:")
print(pd.DataFrame(X_train_scaled, columns=X.columns).describe().loc[['mean', 'std']])

# Import kNeighborsclassifier
from sklearn.neighbors import KNeighborsClassifier
knn.fit(X_train_scaled, y_train)

#setup arrays to store training and test accuracies
neighbors=np.arange(1,10)
train_accuracy_list=[]
test_accuracy_list=[]

"""PREDICTION"""

# Predictions for both train and test sets
y_train_pred = knn.predict(X_train_scaled)
y_test_pred = knn.predict(X_test_scaled)
print(y_train_pred)
print(y_test_pred)

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Create synthetic data (guaranteed to work)
# Ensure n_informative + n_redundant + n_repeated <= n_features
X, y = make_classification(n_samples=1000, n_features=3, n_informative=2, n_redundant=1, n_repeated=0, n_classes=2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Added random_state for reproducibility

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scaled, y_train)

print("Train accuracy:", knn.score(X_train_scaled, y_train)*100)
print("Test accuracy:", knn.score(X_test_scaled, y_test)*100)

import matplotlib.pyplot as plt
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Sample data preparation (replace with your actual data)
X = np.random.rand(100, 3)  # 100 movies, 3 features (action, comedy, drama)
y = np.random.randint(0, 2, 100)  # Binary recommendations

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Evaluate different k values
k_values = range(1, 21)
train_acc = []
test_acc = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    train_acc.append(knn.score(X_train_scaled, y_train))
    test_acc.append(knn.score(X_test_scaled, y_test))

# Find optimal k
optimal_k = k_values[np.argmax(test_acc)]

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(k_values, train_acc, 'bo-', label='Training Accuracy', markersize=8, linewidth=2)
plt.plot(k_values, test_acc, 'rs-', label='Test Accuracy', markersize=8, linewidth=2)
plt.axvline(x=optimal_k, color='green', linestyle='--', label=f'Optimal k={optimal_k}')
plt.title('Movie Recommendation Model Performance', fontsize=14, pad=20)
plt.xlabel('Number of Neighbors (k)', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.xticks(k_values)
plt.grid(True, alpha=0.3)
plt.legend(fontsize=10, frameon=True)
plt.tight_layout()

# Annotate the optimal point
max_test_acc = max(test_acc)
plt.annotate(f'Max Test Acc: {max_test_acc:.2%}',
             xy=(optimal_k, max_test_acc),
             xytext=(optimal_k+2, max_test_acc-0.1),
             arrowprops=dict(facecolor='black', shrink=0.05))

plt.show()

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Sample data
X, y = make_classification(n_samples=1000, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=200)

# Train model
model = LogisticRegression()
model.fit(X_train, y_train)

# Get predictions (properly flattened)
y_pred = model.predict(X_test).flatten()

# One-line metrics with safety
print(f"Precision: {precision_score(y_test, y_pred):.2f}, Recall: {recall_score(y_test, y_pred):.2f}, F1: {f1_score(y_test, y_pred):.2f}")

# For rating prediction (1-5 stars)
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['1★', '2★', '3★', '4★', '5★'],
            yticklabels=['1★', '2★', '3★', '4★', '5★'])
plt.title('Movie Rating Prediction Confusion Matrix')
plt.xlabel('Predicted Rating')
plt.ylabel('Actual Rating')
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming you have:
# y_test = true labels (0=Not Recommended, 1=Recommended)
# y_pred = predicted labels

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Plot with movie recommendation labels
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Recommended', 'Recommended'],
            yticklabels=['Not Recommended', 'Recommended'])
plt.title('Movie Recommendation Confusion Matrix')
plt.xlabel('Predicted Recommendation')
plt.ylabel('Actual Recommendation')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Sample movie dataset (replace with your data)
data = {
    'title': ['The Dark Knight', 'Inception', 'Toy Story', 'The Godfather', 'Forrest Gump',
              'Pulp Fiction', 'Fight Club', 'The Matrix', 'Goodfellas', 'The Shawshank Redemption'],
    'action': [1, 1, 0, 0, 0, 1, 1, 1, 0, 0],
    'comedy': [0, 0, 1, 0, 1, 1, 0, 0, 0, 0],
    'drama': [0, 0, 0, 1, 1, 0, 1, 0, 1, 1],
    'true_genre': ['action', 'action', 'comedy', 'drama', 'drama',
                  'comedy', 'drama', 'action', 'drama', 'drama']
}
movies = pd.DataFrame(data)

# Prepare data
X = movies[['action', 'comedy', 'drama']]
y = movies['true_genre']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train classifier
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

# Predictions
y_pred = clf.predict(X_test)

# Generate confusion matrix
labels = ['action', 'comedy', 'drama']
cm = confusion_matrix(y_test, y_pred, labels=labels)

# Visualization
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels,
            yticklabels=labels,
            cbar_kws={'label': 'Number of Movies'})
plt.title('Movie Genre Classification Confusion Matrix', pad=20, fontsize=14)
plt.xlabel('Predicted Genre', fontsize=12)
plt.ylabel('Actual Genre', fontsize=12)
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.tight_layout()

# Add accuracy annotations
for i in range(len(labels)):
    for j in range(len(labels)):
        accuracy = cm[i,j]/cm[i].sum()
        if cm[i,j] > 0:
            plt.text(j+0.5, i+0.5, f"{accuracy:.0%}",
                    ha='center', va='center', color='red')

plt.show()

"""USER INPUT FOR MOVIE RECOMMENDATION"""

import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Sample movie data
data = {
    'movie_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'title': ['The Dark Knight', 'Inception', 'Interstellar', 'Pulp Fiction',
             'Fight Club', 'Forrest Gump', 'The Matrix', 'Goodfellas',
             'The Shawshank Redemption', 'The Godfather'],
    'action': [1, 1, 1, 1, 1, 0, 1, 0, 0, 0],
    'comedy': [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
    'drama': [0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
    'rating': [4.5, 4.7, 4.8, 4.9, 4.6, 4.2, 4.7, 4.4, 4.9, 4.8]
}
movies = pd.DataFrame(data)

# Prepare features and target
features = ['action', 'comedy', 'drama']
X = movies[features]
y = movies['rating'] > 4.5  # Recommend if rating > 4.5

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train KNN model
knn = NearestNeighbors(n_neighbors=3, metric='cosine')
knn.fit(X_train_scaled)

# Recommendation function
def get_recommendations(action_pref, comedy_pref, drama_pref):
    user_input = [[action_pref, comedy_pref, drama_pref]]
    user_scaled = scaler.transform(user_input)
    distances, indices = knn.kneighbors(user_scaled)

    recommendations = []
    for i in indices[0]:
        movie = movies.iloc[i]
        recommendations.append({
            'title': movie['title'],
            'rating': movie['rating'],
            'match_score': 1 - distances[0][list(indices[0]).index(i)]
        })
    return recommendations

# Interactive input
print("=== Movie Recommendation System ===")
print("Rate your preference for each genre (0-1 scale):")
action = float(input("Action preference (0-1): "))
comedy = float(input("Comedy preference (0-1): "))
drama = float(input("Drama preference (0-1): "))

# Get recommendations
recs = get_recommendations(action, comedy, drama)

# Display results
print("\n=== Training & Evaluation ===")
print(f"Model trained on {len(X_train)} movies")
print(f"Test set contains {len(X_test)} movies")
print(f"Recommendation threshold: Rating > 4.5\n")

print("=== Your Recommendations ===")
for i, movie in enumerate(recs, 1):
    print(f"{i}. {movie['title']}")
    print(f"   Rating: {movie['rating']:.1f}")
    print(f"   Match score: {movie['match_score']:.2f}\n")